"""Sinks: where the pipeline's records go."""

from typing import Protocol

from trafficcam.contracts import Clip, ClipDeleted, Event, GroupState, Passage, SignalChange


class EventSink(Protocol):
    def passage(self, passage: Passage) -> None: ...

    def event(self, event: Event) -> None: ...

    def signal(self, change: SignalChange) -> None: ...

    def group_state(self, state: GroupState) -> None: ...

    def clip(self, clip: Clip) -> None: ...

    def clip_deleted(self, deleted: ClipDeleted) -> None: ...

    def close(self) -> None: ...
