//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace TrafficCam.Contracts
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SignalState
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"red")]
        [System.Runtime.Serialization.EnumMember(Value = @"red")]
        Red = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"red_amber")]
        [System.Runtime.Serialization.EnumMember(Value = @"red_amber")]
        RedAmber = 1,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"green")]
        [System.Runtime.Serialization.EnumMember(Value = @"green")]
        Green = 2,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"amber")]
        [System.Runtime.Serialization.EnumMember(Value = @"amber")]
        Amber = 3,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"unknown")]
        [System.Runtime.Serialization.EnumMember(Value = @"unknown")]
        Unknown = 4,


    }

    /// <summary>
    /// observed: read from a visible signal head. inferred: estimated for a head that cannot be seen.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SignalSource
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"observed")]
        [System.Runtime.Serialization.EnumMember(Value = @"observed")]
        Observed = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"inferred")]
        [System.Runtime.Serialization.EnumMember(Value = @"inferred")]
        Inferred = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum RoadUserClass
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"car")]
        [System.Runtime.Serialization.EnumMember(Value = @"car")]
        Car = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"truck")]
        [System.Runtime.Serialization.EnumMember(Value = @"truck")]
        Truck = 1,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"bus")]
        [System.Runtime.Serialization.EnumMember(Value = @"bus")]
        Bus = 2,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"motorcycle")]
        [System.Runtime.Serialization.EnumMember(Value = @"motorcycle")]
        Motorcycle = 3,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"bicycle")]
        [System.Runtime.Serialization.EnumMember(Value = @"bicycle")]
        Bicycle = 4,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"person")]
        [System.Runtime.Serialization.EnumMember(Value = @"person")]
        Person = 5,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum VisionState
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"online")]
        [System.Runtime.Serialization.EnumMember(Value = @"online")]
        Online = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"offline")]
        [System.Runtime.Serialization.EnumMember(Value = @"offline")]
        Offline = 1,


    }

    /// <summary>
    /// One completed road-user trip through the junction. Topic: trafficcam/v1/passages.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Passage
    {

        [System.Text.Json.Serialization.JsonPropertyName("schema")]
        public required string Schema { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required System.Guid Id { get; set; }

        /// <summary>
        /// When the passage closed.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("ts")]
        public required System.DateTimeOffset Ts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("camera")]
        public required string Camera { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("config_hash")]
        public required string ConfigHash { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("first_seen")]
        public required System.DateTimeOffset FirstSeen { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("last_seen")]
        public required System.DateTimeOffset LastSeen { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("track_id")]
        public required int? TrackId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("class")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<RoadUserClass>))]
        public required RoadUserClass? Class { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("entry_zone")]
        public required string? EntryZone { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("exit_zone")]
        public required string? ExitZone { get; set; }

        /// <summary>
        /// For example 'south-&gt;east'.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("movement")]
        public required string? Movement { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("stopline")]
        public required string? Stopline { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("stopline_crossed_at")]
        public required System.DateTimeOffset? StoplineCrossedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("signal_state_at_crossing")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SignalState>))]
        public required SignalState? SignalStateAtCrossing { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("signal_source")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SignalSource>))]
        public required SignalSource? SignalSource { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("speed_kmh")]
        public required double? SpeedKmh { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("flags")]
        public required System.Collections.Generic.IDictionary<string, object> Flags { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// One detector event. Topic: trafficcam/v1/events/{type}.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Event
    {

        [System.Text.Json.Serialization.JsonPropertyName("schema")]
        public required string Schema { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required System.Guid Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ts")]
        public required System.DateTimeOffset Ts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("camera")]
        public required string Camera { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("config_hash")]
        public required string ConfigHash { get; set; }

        /// <summary>
        /// Detector event type, for example 'box_junction_stop'.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public required string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("detector_version")]
        public required string DetectorVersion { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("passage_id")]
        public required System.Guid? PassageId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("track_id")]
        public required int? TrackId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("class")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<RoadUserClass>))]
        public required RoadUserClass? Class { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("confidence")]
        public required double? Confidence { get; set; }

        /// <summary>
        /// Detector-specific attributes.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("attrs")]
        public required System.Collections.Generic.IDictionary<string, object> Attrs { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("clip_id")]
        public required System.Guid? ClipId { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// A signal head changed state. Topic: trafficcam/v1/signals/{head_id}, retained.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class SignalChange
    {

        [System.Text.Json.Serialization.JsonPropertyName("schema")]
        public required string Schema { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required System.Guid Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ts")]
        public required System.DateTimeOffset Ts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("camera")]
        public required string Camera { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("config_hash")]
        public required string ConfigHash { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("head_id")]
        public required string HeadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("from_state")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SignalState>))]
        public required SignalState? FromState { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("to_state")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SignalState>))]
        public required SignalState ToState { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("source")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SignalSource>))]
        public required SignalSource Source { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("confidence")]
        public required double? Confidence { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// One reason a clip was recorded: a detector event, or a manual command.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ClipTrigger
    {

        /// <summary>
        /// The event's type, or 'manual'.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public required string Type { get; set; }

        /// <summary>
        /// When it happened.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("at")]
        public required System.DateTimeOffset At { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("event_id")]
        public required System.Guid? EventId { get; set; }

        /// <summary>
        /// The text of a manual command.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        public required string? Reason { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// A clip file was closed. `id` is the clip id. Topic: trafficcam/v1/clips/{clip_id}.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Clip
    {

        [System.Text.Json.Serialization.JsonPropertyName("schema")]
        public required string Schema { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required System.Guid Id { get; set; }

        /// <summary>
        /// When the file was closed.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("ts")]
        public required System.DateTimeOffset Ts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("camera")]
        public required string Camera { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("config_hash")]
        public required string ConfigHash { get; set; }

        /// <summary>
        /// The first trigger's event.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("event_id")]
        public required System.Guid? EventId { get; set; }

        /// <summary>
        /// Everything the clip was recorded for, in the order it happened.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("triggers")]
        public required System.Collections.Generic.ICollection<ClipTrigger> Triggers { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("path")]
        public required string Path { get; set; }

        /// <summary>
        /// Still frame from the event moment.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("keyframe_path")]
        public required string? KeyframePath { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("started_at")]
        public required System.DateTimeOffset StartedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ended_at")]
        public required System.DateTimeOffset EndedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("bytes")]
        public required long Bytes { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// A signal group's state. Topic: trafficcam/v1/groups/{group}, retained; or .../settled.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GroupState
    {

        [System.Text.Json.Serialization.JsonPropertyName("schema")]
        public required string Schema { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required System.Guid Id { get; set; }

        /// <summary>
        /// When the group came to be in this state.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("ts")]
        public required System.DateTimeOffset Ts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("camera")]
        public required string Camera { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("config_hash")]
        public required string ConfigHash { get; set; }

        /// <summary>
        /// Heads that change together, as named in the site's signal plan.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("group")]
        public required string Group { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("state")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SignalState>))]
        public required SignalState State { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("source")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SignalSource>))]
        public required SignalSource? Source { get; set; }

        /// <summary>
        /// True for the state as known some time on; false for it as known at once.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("settled")]
        public required bool Settled { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// A clip's files were deleted. `id` is the clip id. Topic: trafficcam/v1/clips/{clip_id}/deleted.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ClipDeleted
    {

        [System.Text.Json.Serialization.JsonPropertyName("schema")]
        public required string Schema { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required System.Guid Id { get; set; }

        /// <summary>
        /// When the files were deleted.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("ts")]
        public required System.DateTimeOffset Ts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("camera")]
        public required string Camera { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Manual clip trigger. Topic: trafficcam/v1/cmd/clip.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ClipCommand
    {

        [System.Text.Json.Serialization.JsonPropertyName("schema")]
        public required string Schema { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required System.Guid Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ts")]
        public required System.DateTimeOffset Ts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("camera")]
        public required string Camera { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        public required string Reason { get; set; }

        /// <summary>
        /// Seconds to keep before the moment it arrives. Absent, the site's default.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pre_s")]
        public double? PreS { get; set; }

        /// <summary>
        /// Seconds to keep after it. Absent, the site's default.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("post_s")]
        public double? PostS { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Keep a clip longer, or not. `id` is the clip id. Topic: trafficcam/v1/cmd/keep/{id}, retained.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ClipKeep
    {

        [System.Text.Json.Serialization.JsonPropertyName("schema")]
        public required string Schema { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required System.Guid Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ts")]
        public required System.DateTimeOffset Ts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("camera")]
        public required string Camera { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("keep")]
        public required bool Keep { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Vision presence; 'offline' is the last will. Topic: trafficcam/v1/status/vision, retained.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Status
    {

        [System.Text.Json.Serialization.JsonPropertyName("schema")]
        public required string Schema { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required System.Guid Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ts")]
        public required System.DateTimeOffset Ts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("camera")]
        public required string Camera { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("state")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<VisionState>))]
        public required VisionState State { get; set; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }
}